// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentMentalHealthMonitoringSystem.Data;

#nullable disable

namespace StudentMentalHealthMonitoringSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260812203636_AddAIChatMonitoring")]
    partial class AddAIChatMonitoring
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("StudentMentalHealthMonitoringSystem.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("longtext");

                    b.HasKey("AdminId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("StudentMentalHealthMonitoringSystem.Models.CSSRSAssessment", b =>
                {
                    b.Property<int>("AssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AssessmentId"));

                    b.Property<string>("AdditionalInformation")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("AssessmentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Question1Answer")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Question2Answer")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Question3Answer")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Question4Answer")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Question5Answer")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Question6Answer")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("RecentBehavior")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RequiresImmediateAction")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("AssessmentId");

                    b.HasIndex("StudentId", "Semester")
                        .IsUnique();

                    b.ToTable("CSSRSAssessments");
                });

            modelBuilder.Entity("StudentMentalHealthMonitoringSystem.Models.ChatMessage", b =>
                {
                    b.Property<int>("ChatMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ChatMessageId"));

                    b.Property<int>("ChatSessionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ChatMessageId");

                    b.HasIndex("ChatSessionId", "CreatedAt");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("StudentMentalHealthMonitoringSystem.Models.ChatRiskAssessment", b =>
                {
                    b.Property<int>("ChatRiskAssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ChatRiskAssessmentId"));

                    b.Property<int>("ChatSessionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RiskStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.HasKey("ChatRiskAssessmentId");

                    b.HasIndex("ChatSessionId");

                    b.HasIndex("StudentId", "CreatedAt");

                    b.ToTable("ChatRiskAssessments");
                });

            modelBuilder.Entity("StudentMentalHealthMonitoringSystem.Models.ChatSession", b =>
                {
                    b.Property<int>("ChatSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ChatSessionId"));

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.HasKey("ChatSessionId");

                    b.HasIndex("StudentId", "IsActive");

                    b.ToTable("ChatSessions");
                });

            modelBuilder.Entity("StudentMentalHealthMonitoringSystem.Models.Counseling", b =>
                {
                    b.Property<int>("CounselingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CounselingId"));

                    b.Property<TimeSpan>("AppointmentEndTime")
                        .HasColumnType("time(6)");

                    b.Property<string>("AppointmentRoom")
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("AppointmentTime")
                        .HasColumnType("time(6)");

                    b.Property<string>("Assessment")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CounselingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NextFollowUpDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Observation")
                        .HasColumnType("longtext");

                    b.Property<int>("PsychologistId")
                        .HasColumnType("int");

                    b.Property<string>("Recommendation")
                        .HasColumnType("longtext");

                    b.Property<string>("RiskLevel")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("CounselingId");

                    b.HasIndex("PsychologistId");

                    b.HasIndex("StudentId");

                    b.ToTable("Counselings");
                });

            modelBuilder.Entity("StudentMentalHealthMonitoringSystem.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("HeadOfDepartment")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("StudentMentalHealthMonitoringSystem.Models.PHQAssessment", b =>
                {
                    b.Property<int>("AssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AssessmentId"));

                    b.Property<string>("AdditionalComments")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("AssessmentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FunctionalDifficulty")
                        .HasColumnType("longtext");

                    b.Property<int>("Question1Score")
                        .HasColumnType("int");

                    b.Property<int>("Question2Score")
                        .HasColumnType("int");

                    b.Property<int>("Question3Score")
                        .HasColumnType("int");

                    b.Property<int>("Question4Score")
                        .HasColumnType("int");

                    b.Property<int>("Question5Score")
                        .HasColumnType("int");

                    b.Property<int>("Question6Score")
                        .HasColumnType("int");

                    b.Property<int>("Question7Score")
                        .HasColumnType("int");

                    b.Property<int>("Question8Score")
                        .HasColumnType("int");

                    b.Property<int>("Question9Score")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresImmediateReview")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SeverityLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.HasKey("AssessmentId");

                    b.HasIndex("StudentId", "Semester")
                        .IsUnique();

                    b.ToTable("PHQAssessments");
                });

            modelBuilder.Entity("StudentMentalHealthMonitoringSystem.Models.Psychologist", b =>
                {
                    b.Property<int>("PsychologistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PsychologistId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("Experience")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("longtext");

                    b.Property<string>("Qualification")
                        .HasColumnType("longtext");

                    b.Property<string>("Specialization")
                        .HasColumnType("longtext");

                    b.HasKey("PsychologistId");

                    b.ToTable("Psychologists");
                });

            modelBuilder.Entity("StudentMentalHealthMonitoringSystem.Models.PsychologistAvailability", b =>
                {
                    b.Property<int>("PsychologistAvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PsychologistAvailabilityId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time(6)");

                    b.Property<int>("PsychologistId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time(6)");

                    b.HasKey("PsychologistAvailabilityId");

                    b.HasIndex("PsychologistId");

                    b.ToTable("PsychologistAvailabilities");
                });

            modelBuilder.Entity("StudentMentalHealthMonitoringSystem.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Department")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FinancialCondition")
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<string>("GuardianEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("GuardianName")
                        .HasColumnType("longtext");

                    b.Property<string>("GuardianPhone")
                        .HasColumnType("longtext");

                    b.Property<double?>("Height")
                        .HasColumnType("double");

                    b.Property<string>("LatestChatRiskStatus")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LatestChatRiskUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("longtext");

                    b.Property<string>("Relationship")
                        .HasColumnType("longtext");

                    b.Property<string>("Semester")
                        .HasColumnType("longtext");

                    b.Property<string>("StudentIdNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double?>("Weight")
                        .HasColumnType("double");

                    b.HasKey("StudentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("StudentMentalHealthMonitoringSystem.Models.StudentAvailability", b =>
                {
                    b.Property<int>("StudentAvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StudentAvailabilityId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time(6)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("StudentAvailabilityId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentAvailabilities");
                });

            modelBuilder.Entity("StudentMentalHealthMonitoringSystem.Models.StudentSemesterRecord", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<string>("AvailableDay")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("time(6)");

                    b.Property<string>("FeelingText")
                        .HasMaxLength(3000)
                        .HasColumnType("varchar(3000)");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("time(6)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("RecordId");

                    b.HasIndex("StudentId", "Semester")
                        .IsUnique();

                    b.ToTable("StudentSemesterRecords");
                });

            modelBuilder.Entity("StudentMentalHealthMonitoringSystem.Models.CSSRSAssessment", b =>
                {
                    b.HasOne("StudentMentalHealthMonitoringSystem.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentMentalHealthMonitoringSystem.Models.ChatMessage", b =>
                {
                    b.HasOne("StudentMentalHealthMonitoringSystem.Models.ChatSession", "ChatSession")
                        .WithMany("ChatMessages")
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("StudentMentalHealthMonitoringSystem.Models.ChatRiskAssessment", b =>
                {
                    b.HasOne("StudentMentalHealthMonitoringSystem.Models.ChatSession", "ChatSession")
                        .WithMany("RiskAssessments")
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentMentalHealthMonitoringSystem.Models.Student", "Student")
                        .WithMany("ChatRiskAssessments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChatSession");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentMentalHealthMonitoringSystem.Models.ChatSession", b =>
                {
                    b.HasOne("StudentMentalHealthMonitoringSystem.Models.Student", "Student")
                        .WithMany("ChatSessions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentMentalHealthMonitoringSystem.Models.Counseling", b =>
                {
                    b.HasOne("StudentMentalHealthMonitoringSystem.Models.Psychologist", "Psychologist")
                        .WithMany()
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentMentalHealthMonitoringSystem.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Psychologist");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentMentalHealthMonitoringSystem.Models.PHQAssessment", b =>
                {
                    b.HasOne("StudentMentalHealthMonitoringSystem.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentMentalHealthMonitoringSystem.Models.PsychologistAvailability", b =>
                {
                    b.HasOne("StudentMentalHealthMonitoringSystem.Models.Psychologist", "Psychologist")
                        .WithMany()
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Psychologist");
                });

            modelBuilder.Entity("StudentMentalHealthMonitoringSystem.Models.StudentAvailability", b =>
                {
                    b.HasOne("StudentMentalHealthMonitoringSystem.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentMentalHealthMonitoringSystem.Models.StudentSemesterRecord", b =>
                {
                    b.HasOne("StudentMentalHealthMonitoringSystem.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentMentalHealthMonitoringSystem.Models.ChatSession", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("RiskAssessments");
                });

            modelBuilder.Entity("StudentMentalHealthMonitoringSystem.Models.Student", b =>
                {
                    b.Navigation("ChatRiskAssessments");

                    b.Navigation("ChatSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
